### ISSUE TITLE
KaTeX Macros do not work

### ISSUE THREAD

**Issue by timm0e** [goessner/mdmath#51]
### Summary

KaTeX says they support Macros: https://github.com/Khan/KaTeX/wiki/Function-Support-in-KaTeX#macros

### Expected behavior

It should define / use the macro

### Actual behavior

The Macro just appears as red text

### Steps to reproduce

1. Try to add a new macro or comment and try to use it
2. Sadly no profit :(

### Code example

```
$\\gdef\test{Test}$
$\gdef\test{Test}$
```

### Related links

* [Markdown+Math](https://github.com/goessner/mdmath)

### Environment

```text
     Operating system: Windows 10
       VSCode version: 1.25.1
Markdown+Math version: 2,2,1
```

**Comment by colinfang** [comment]
The current `Katex` used here is pinned as 0.9.0, perhaps the author would release a new version when v0.10.0 is released which is the stable version that contains macros.

**Comment by colinfang** [comment]
I have a feature patch that enables the KaTeX macros. The macros `gdef` defined in any code blocks are file persistent. Also I added a config that is able to define macros that are workspace persistent. 

https://github.com/goessner/mdmath/compare/master...colinfang:master

I wonder if @goessner  is happy to absorb such feature.

E.g.

```
        "mdmath.globalMacros": {
          "type": "array",
          "default": [
            "\\gdef\\E#1{\\operatorname{\\mathbb{E}}\\!\\big[#1\\big]}",
            "\\gdef\\Eq#1#2{\\operatorname{\\mathbb{E}}_{#1}\\!\\big[#2\\big]}"
          ],
          "items": "string",
          "description": "A list of global macros"
```

**Comment by goessner** [comment]
@colinfang :  This sounds very good.

I am currently extremely busy within another project. I should have told you earlier.

I will come back to you in time.

Thanks

**Comment by goessner** [comment]
@colinfang : With mdmath 2.3.0 KaTeX 0.10.0-beta is supported.

I also implemented your 'global macros' approach.

Thanks

I

**Comment by colinfang** [comment]
@goessner  Have you missed the update to markdown-it-texmath for the globalMacros?

https://github.com/goessner/markdown-it-texmath/compare/master...colinfang:master

**Comment by goessner** [comment]
.. yes , I did,

Is it necessary, to do that 

```js
    if (!env.texmathMacros) {
        env.texmathMacros = Object.assign({}, texmath.globalMacros);
    }
```

inside of the critical `texmath.render` function ?

**Comment by colinfang** [comment]
Apart from the global macros, I would also like to make macros which are defined in a code block to be available to other code blocks in the same .md file, but not to other files.

- The scope of the global macros defined in the config is the whole workspace.
- The scope of the `\gdef` macros defined in a code block is the whole file below the code block.

`env` is a shared object (within a .md file) from `markdown-it`. KaTex would insert `\gdef` macro into the `macro` object passed in at each render, which I then pass it to the next `render` via `env`.

If you don't like the idea of file persistent macro, the logic can be simplified I think.

My markdown-it knowledge is limited. so is my js skill. Perhaps you can find better ways to do it.

**Comment by goessner** [comment]
Yes, I like the idea.

I would rather like to have user specific macros instead. May be these can go into VSCode user settings or a user specific file.

I need to ensure, that the majority of users not using macros won't get a performance penalty by this.

So I must dive a little deeper into this, for what I currently don't have the time.

So I want to deactivate global macros for now and come back to you in time.

Thanks.

**Comment by danmackinlay** [comment]
Speaking as a working mathematician who occasionally tries to persuade colleagues to put mathematics online using something other than PDFs... No one in my community at least will accept using a math rendering package which does not include mathematics macros, as it is part of the established workflow. So possibly one part of the reason that the majority of users do not use macros is that we are preventing mathematicians, who at least in my experience are completely macro-dependent, from joining us.

I am aware this comment adds no useful code to solve this problem, but I do think this perspective on the users is important.

**Comment by goessner** [comment]
Macros do work now with mdmath 2.3.5+ ...
