### ISSUE TITLE
Bracket delimiters don't work

### ISSUE THREAD

**Issue by danmackinlay** [goessner/mdmath#66]
### Summary

I'm opening this issue here because I wasted some time thinking it was a problem with this project.

If you use brackets as delimiters in mdmath, you may find problems rendering; in particular, square brackets don't work reliably:

### Expected behavior
markdown like this

```markdown
\[f^2\] \(f^3\)
```
should always be rendered a mathematics

### Actual behavior

Sometimes the square bracket math markup does not work

![failure in markdown bracket delimiter rendering](https://user-images.githubusercontent.com/21740/52096205-2b5c8680-261a-11e9-9415-43f0bff9c9b3.png)

### Related links

This is in fact not due to this project *per se* but 
[a bug](https://github.com/goessner/markdown-it-texmath/issues/9)
in the underlying markdown parser
[markdown-it-texmath](https://github.com/goessner/markdown-it-texmath/).
I mention it here so that other people are not confused by this behaviour.
We might wish to indicate this in the documentation until we get around to filing fixes.

**Comment by goessner** [comment]
Resolved by update with respect to update of [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath) to version 0.5.5 due to resolved  [rendering bug with brackets delimiters](https://github.com/goessner/markdown-it-texmath/issues/9).

Thanks.

**Comment by ashlesss** [comment]
I think this bug is still persisting. 

I have following content:
```markdown
123
\[
H = \Delta \begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix},
\]
```

And the result will be:
```
123 [ H = \Delta \begin{bmatrix} 0 & 1 \ 1 & 0 \end{bmatrix}, ]
```

But the correct result should be: 
![image](https://github.com/goessner/mdmath/assets/69986428/2cfef1ce-fc22-4dd9-9042-9a268c35ae40)

When I am trying to fix this, just modify the content like this:
```markdown
123

\[
H = \Delta \begin{bmatrix}
0 & 1 \\
1 & 0
\end{bmatrix},
\]
``` 

And it will produce the correct result.
