### ISSUE TITLE
Crashing & Incorrect display math rendering inside blockquotes

### ISSUE THREAD

**Issue by nfbyte** [goessner/mdmath#89]
### Summary 1
(I'm using the GitLab delimiters setting)
The following code crashes the mdmath extension (similar to #50):
~~~
>```math
blabla
```
~~~
Log:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF708B328AE uv_gettimeofday+11629934
 2: 00007FF708008236 node::Abort+22
 3: 00007FF7080082A3 node::Abort+131
 4: 00007FF705C38F28 v8::V8::GetVersion+792
 5: 00007FF705C38ECA v8::V8::GetVersion+698
 6: 00007FF705C7D7C3 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+59155
 7: 00007FF705C7ED74 std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+64708
 8: 00007FF705C7BCFB std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+52299
 9: 00007FF705C79CAE std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+44030
10: 00007FF705C841AC std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+86268
11: 00007FF705C8461D std::_Vector_alloc<std::_Vec_base_types<v8::CpuProfileDeoptFrame,std::allocator<v8::CpuProfileDeoptFrame> > >::_Make_iterator+87405
12: 00007FF705E57FA2 v8::Unlocker::~Unlocker+52386
13: 00007FF7060A7560 v8::internal::TickSample::print+475984
14: 00007FF70664983D v8_inspector::V8ContextInfo::executionContextId+3229005
15: 0000038BD482AF86 
```

### Summary 2
Also, display math inside blockquotes is not rendered properly in the VSCode preview.

### Expected behavior
```
>```math
>\frac{1}{2}
>```
```
and
```
> ```math
> \frac{1}{2}
> ```
```
should render to:
![](https://i.imgur.com/Cdane0d.png)
inside a blockquote.
### Actual behavior
```
>```math
>\frac{1}{2}
>```
```
doesn't render at all, and
```
> ```math
> \frac{1}{2}
> ```
```
renders to:
![](https://i.imgur.com/M8zw9Xl.png)
inside a blockquote.

### Environment

```text
     Operating system: Windows 10 64bit
       VSCode version: 1.44.2
Markdown+Math version: 2.4.0
```

**Comment by goessner** [comment]
yes ... I was able to reproduce that bug. In fact it was independent of the rules set.

With new Version 2.5 please test it, I already did it and the bug should be resolved now.

Please note, that with multiline display formulas in blockquote blocks you need to start each new (formula) line with a `>` character, as in 
```
>```math
>\frac{1}{2}
>```
```
A whitespace character is allowed but not needed after the  `>` character. Multilevel blockquote blocks are also supported now.

You can also write your formula on a single line, as in

```
> ```math \frac{1}{2} ```
```

thanks

**Comment by deb-master** [comment]
Sorry for the late reply, I just tested it and the issues are not resolved. The crashing still occurs and the display bug is only partially fixed.

```
>```math
>\frac{1}{2}
>```
```
doesn't render at all, and
```
> ```math
> \frac{1}{2}
> ```
```
renders to:
![](https://i.imgur.com/0ox90XZ.png)

Please re-open.

### Environment

```text
     Operating system: Windows 10 64bit
       VSCode version: 1.46.1
Markdown+Math version: 2.5.1
```
